### ISSUE TITLE
Can't type . when input type is decimal

### ISSUE THREAD

**Issue by sportywide** [pksilen/semantic-ui-react-numberinput#3]
Hello, 
When the valueType is set to decimal, I cannot enter the decimal point, e.g. "9.". The value is always rounded to an integer. This makes it not possible to enter decimal values like "9.23" without using the step button. Is it possible to fix this?

**Comment by pksilen** [comment]
Corrected in version 1.3.6

**Comment by tomitrescak** [comment]
I still cannot type decimals :/ Is there a regression ? Thanks!

**Comment by pksilen** [comment]
I cannot reproduce that fault. Can you describe me what value and how are you trying to enter it? What props did you give for NumberInput component?

**Comment by tomitrescak** [comment]
@pksilen .... I apologise, the issue was with the Formix behind, not with your control.
